#!/bin/sh
set -e

ARCH=$(uname -m)
if [ "$ARCH" != "x86_64" ]; then
    echo "Only x86_64 architecture is supported."
    exit 1
fi

LATEST_MONERO=$(curl -s https://api.github.com/repos/monero-project/monero/releases/latest|python -c "import json, sys; print(json.load(sys.stdin)['tag_name'])")

download "https://downloads.getmonero.org/cli/monero-linux-x64-${LATEST_MONERO}.tar.bz2" | tar jxvf - -C /tmp
mv /tmp/monero-*/monerod /tmp/monero-*/monero-wallet-cli /tmp/monero-*/monero-blockchain-stats /usr/bin/

download $(get-github-download-url SChernykh p2pool '.*-linux-x64\.tar\.gz$') | tar zxvf - -C /tmp
mv /tmp/p2pool-*/p2pool /usr/bin/
